### ISSUE TITLE
Any additional documentation/clarification?

### ISSUE THREAD

**Issue by pcolmer** [larsks/crowd-pubtkt#1]
If I understand correctly, I can be using mod_auth_pubtkt on my Apache site(s) and point it at a server running crowd-pubtkt. The user goes to one of my Apache sites, gets redirected to the crowd-pubtkt server, logs in, a token gets generated and returned to the calling server?

Presumably if a pubtkt token already exists the user doesn't log in?

Your README file says that authentication is handled using mod_authnz_crowd but the sample Apache configuration file doesn't make reference to that.

Can you please provide some additional details around what steps are required to get a server up and running with this code?

Thanks.

**Comment by larsks** [comment]
I apologize, but it's been five yers (!) since I last looked at this code, and I no longer work in an environment where we're using crowd.  Or mod_auth_pubtkt.  I can't even remember if this code was ever functional.  Sorry!
